#!/usr/bin/env python2.7
# coding: UTF-8

import argparse
import os
import posixpath
import sys
import SimpleHTTPServer
import SocketServer

class Server(SocketServer.TCPServer):

    allow_reuse_address = True

    def __init__(self, *args, **kwargs):
        SocketServer.TCPServer.__init__(self, *args, **kwargs)


class Handler(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        SimpleHTTPServer.SimpleHTTPRequestHandler.__init__(
                self, *args, **kwargs)

    def guess_type(self, path):
        basename = posixpath.basename(path)
        if basename[0] in "▁▂▃▅▆▇":
            return 'text/html'
        return SimpleHTTPServer.SimpleHTTPRequestHandler.guess_type(self, path)

def main():

    parser = argparse.ArgumentParser(description='Simple web server.',
            add_help=False)
    parser.add_argument('directory', nargs='?', default='.')
    parser.add_argument('--help', type=bool)
    parser.add_argument('-h', '--host', default='localhost')
    parser.add_argument('-p', '--port', type=int, default=8123)

    args = vars(parser.parse_args())

    if args['help']:
        parser.print_help()
        return

    os.chdir(args['directory'])
    host = args['host']
    port = args['port']

    httpd = Server((host, port), Handler)

    print "Serving HTTP at %s:%d" % (host, port)
    httpd.serve_forever()

if __name__ == '__main__':
    sys.exit(main())
