#!/usr/bin/env python2.7
# coding: UTF-8

import SimpleHTTPServer
import SocketServer
import posixpath

PORT = 8123

class Handler(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        SimpleHTTPServer.SimpleHTTPRequestHandler.__init__(
                self, *args, **kwargs)

    def guess_type(self, path):
        basename = posixpath.basename(path)
        if basename[0] in "▁▂▃▅▆▇":
            return 'text/html'
        return SimpleHTTPServer.SimpleHTTPRequestHandler.guess_type(self, path)

httpd = SocketServer.TCPServer(("", PORT), Handler)

print "serving at localhost:%d" % (PORT, )
httpd.serve_forever()
